/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ListSort */

#ifndef _Included_ListSort
#define _Included_ListSort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ListSort
 * Method:    sort
 * Signature: ([F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_ListSort_sort
        (JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif